# Generated by Django 4.1.10 on 2023-12-10 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookmarkCollection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookmark_collections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Bookmark Collection",
                "verbose_name_plural": "Bookmark Collections",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Bookmark",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "internal_id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "bookmark_type",
                    models.CharField(
                        choices=[
                            ("ARTICLE", "Article"),
                            ("VIDEO", "Video"),
                            ("SOCIAL_POST", "Social Post"),
                            ("LINK", "Link"),
                            ("EMAIL", "Email"),
                            ("PERSON", "Person"),
                        ],
                        max_length=100,
                    ),
                ),
                ("link", models.URLField(max_length=255)),
                ("archived", models.BooleanField(default=False)),
                (
                    "collections",
                    models.ManyToManyField(
                        related_name="bookmarks", to="main.bookmarkcollection"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookmarks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="bookmarkcollection",
            index=models.Index(
                fields=["created_by", "name"], name="created_by__name__idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="bookmarkcollection",
            unique_together={("created_by", "name")},
        ),
    ]
