# Generated by Django 4.1.10 on 2023-12-27 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_bookmarkcollection_bookmark_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bookmark",
            old_name="bookmark_type",
            new_name="link_type",
        ),
    ]
