# Generated by Django 5.0.1 on 2024-01-10 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_rename_bookmark_type_bookmark_link_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookmark",
            name="link_type",
            field=models.CharField(
                choices=[
                    ("ARTICLE", "Article"),
                    ("VIDEO", "Video"),
                    ("SOCIAL_POST", "Social Post"),
                    ("LINK", "Link"),
                    ("EMAIL", "Email"),
                    ("PERSON", "Person"),
                    ("BOOK", "Book"),
                ],
                max_length=100,
            ),
        ),
    ]
