
version: "3.8"

services:
  caddy:
    restart: unless-stopped
    image: caddy:2.6.2
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile  # configuration
      - caddy-config:/config  # configuration autosaves
      - caddy-data:/data  # saving certificates
      - /data/bookmarks/log:/var/log:rw
    env_file:
      - ../.env
    ports:
      - "80:80/tcp"
      - "443:443/tcp"

  postgres:
    restart: unless-stopped
    image: postgres:15
    container_name: bookmarks_postgres
    volumes:
      - /data/postgresql/data:/var/lib/postgresql/data
      - /data:/data:rw
    env_file:
      - ../.env
    ports:
      - "5432:5432"


volumes:
  caddy-config:
  caddy-data:
